### ISSUE TITLE
LICENSE 좀 추가해 주세요.

### ISSUE THREAD

**Issue by suapapa** [dojinkimm/sample-app#3]
라이선스 파일이 없어서 어떻게 쓸 수 있는지 알 수 없고,
pkg.go.dev 에서도 문서가 보이지 않고 있어요.

**Comment by dojinkimm** [comment]
네 관심 가져주셔서 감사합니다 :) 작업을 하다 말긴 했는데, 곧 업데이트 하겠습니다

**Comment by dojinkimm** [comment]
@suapapa  LICENSE는 MIT로 추가했습니다. 처음 Golang 시작할때 재미삼아 만들어본 repo라서 유지보수를 못하긴 했습니다 :( 필요한 기능들 있으시면 제안 주시면 감사하겠습니다. `pkg.go.dev`는 존재하긴 합니다 https://pkg.go.dev/github.com/dojinkimm/go-krx
